all: 
	lhs2TeX --agda -o C.tex Report.tex
	pdflatex C.tex
#52 repetitions...
#dvipdf C.dvi
#	bibtex C
#	pdflatex C.tex
#	pdflatex C.tex
# \newcommand{\anonymous}{\kern0.06em \vbox to -1 pt {\hrule\@width.5em}}

clean:
	rm -f C.*
